//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFolderHierarchyGUI {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Form1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form1() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFolderHierarchyGUI.Form1", typeof(Form1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=6,Y=107}.
        /// </summary>
        public static System.Drawing.Point btnAjouter_Location {
            get {
                object obj = ResourceManager.GetObject("btnAjouter.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Size semblable à {Width=168, Height=32}.
        /// </summary>
        public static System.Drawing.Size btnAjouter_Size {
            get {
                object obj = ResourceManager.GetObject("btnAjouter.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 11.
        /// </summary>
        public static int btnAjouter_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnAjouter.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string btnAjouter_Text {
            get {
                return ResourceManager.GetString("btnAjouter.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=189}.
        /// </summary>
        public static System.Drawing.Point btnCreer_Location {
            get {
                object obj = ResourceManager.GetObject("btnCreer.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Size semblable à {Width=119, Height=41}.
        /// </summary>
        public static System.Drawing.Size btnCreer_Size {
            get {
                object obj = ResourceManager.GetObject("btnCreer.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 12.
        /// </summary>
        public static int btnCreer_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnCreer.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer.
        /// </summary>
        public static string btnCreer_Text {
            get {
                return ResourceManager.GetString("btnCreer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=146}.
        /// </summary>
        public static System.Drawing.Point btnEffacer_Location {
            get {
                object obj = ResourceManager.GetObject("btnEffacer.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Size semblable à {Width=119, Height=37}.
        /// </summary>
        public static System.Drawing.Size btnEffacer_Size {
            get {
                object obj = ResourceManager.GetObject("btnEffacer.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 16.
        /// </summary>
        public static int btnEffacer_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnEffacer.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Effacer.
        /// </summary>
        public static string btnEffacer_Text {
            get {
                return ResourceManager.GetString("btnEffacer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=15,Y=42}.
        /// </summary>
        public static System.Drawing.Point btnSession_Location {
            get {
                object obj = ResourceManager.GetObject("btnSession.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Size semblable à {Width=542, Height=23}.
        /// </summary>
        public static System.Drawing.Size btnSession_Size {
            get {
                object obj = ResourceManager.GetObject("btnSession.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 3.
        /// </summary>
        public static int btnSession_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnSession.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commencer session.
        /// </summary>
        public static string btnSession_Text {
            get {
                return ResourceManager.GetString("btnSession.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=159,Y=189}.
        /// </summary>
        public static System.Drawing.Point btnVider_Location {
            get {
                object obj = ResourceManager.GetObject("btnVider.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Size semblable à {Width=107, Height=41}.
        /// </summary>
        public static System.Drawing.Size btnVider_Size {
            get {
                object obj = ResourceManager.GetObject("btnVider.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 13.
        /// </summary>
        public static int btnVider_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnVider.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vider.
        /// </summary>
        public static string btnVider_Text {
            get {
                return ResourceManager.GetString("btnVider.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à lundi.
        /// </summary>
        public static string clbJours_Items {
            get {
                return ResourceManager.GetString("clbJours.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mardi.
        /// </summary>
        public static string clbJours_Items1 {
            get {
                return ResourceManager.GetString("clbJours.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mercredi.
        /// </summary>
        public static string clbJours_Items2 {
            get {
                return ResourceManager.GetString("clbJours.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à jeudi.
        /// </summary>
        public static string clbJours_Items3 {
            get {
                return ResourceManager.GetString("clbJours.Items3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vendredi.
        /// </summary>
        public static string clbJours_Items4 {
            get {
                return ResourceManager.GetString("clbJours.Items4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=191,Y=45}.
        /// </summary>
        public static System.Drawing.Point clbJours_Location {
            get {
                object obj = ResourceManager.GetObject("clbJours.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Size semblable à {Width=75, Height=94}.
        /// </summary>
        public static System.Drawing.Size clbJours_Size {
            get {
                object obj = ResourceManager.GetObject("clbJours.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 7.
        /// </summary>
        public static int clbJours_TabIndex {
            get {
                object obj = ResourceManager.GetObject("clbJours.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cours.
        /// </summary>
        public static string cours_Text {
            get {
                return ResourceManager.GetString("cours.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 130.
        /// </summary>
        public static int cours_Width {
            get {
                object obj = ResourceManager.GetObject("cours.Width", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=12,Y=71}.
        /// </summary>
        public static System.Drawing.Point grpSessionActive_Location {
            get {
                object obj = ResourceManager.GetObject("grpSessionActive.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Size semblable à {Width=545, Height=236}.
        /// </summary>
        public static System.Drawing.Size grpSessionActive_Size {
            get {
                object obj = ResourceManager.GetObject("grpSessionActive.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 0.
        /// </summary>
        public static int grpSessionActive_TabIndex {
            get {
                object obj = ResourceManager.GetObject("grpSessionActive.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Session active.
        /// </summary>
        public static string grpSessionActive_Text {
            get {
                return ResourceManager.GetString("grpSessionActive.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à jours.
        /// </summary>
        public static string jours_Text {
            get {
                return ResourceManager.GetString("jours.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 130.
        /// </summary>
        public static int jours_Width {
            get {
                object obj = ResourceManager.GetObject("jours.Width", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à True.
        /// </summary>
        public static bool lblJoursCours_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblJoursCours.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=188,Y=16}.
        /// </summary>
        public static System.Drawing.Point lblJoursCours_Location {
            get {
                object obj = ResourceManager.GetObject("lblJoursCours.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Size semblable à {Width=76, Height=13}.
        /// </summary>
        public static System.Drawing.Size lblJoursCours_Size {
            get {
                object obj = ResourceManager.GetObject("lblJoursCours.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 8.
        /// </summary>
        public static int lblJoursCours_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblJoursCours.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jours du cours.
        /// </summary>
        public static string lblJoursCours_Text {
            get {
                return ResourceManager.GetString("lblJoursCours.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à True.
        /// </summary>
        public static bool lblNom_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblNom.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=6,Y=35}.
        /// </summary>
        public static System.Drawing.Point lblNom_Location {
            get {
                object obj = ResourceManager.GetObject("lblNom.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Size semblable à {Width=76, Height=13}.
        /// </summary>
        public static System.Drawing.Size lblNom_Size {
            get {
                object obj = ResourceManager.GetObject("lblNom.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 9.
        /// </summary>
        public static int lblNom_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblNom.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du cours:.
        /// </summary>
        public static string lblNom_Text {
            get {
                return ResourceManager.GetString("lblNom.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à True.
        /// </summary>
        public static bool lblSession_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblSession.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=12,Y=12}.
        /// </summary>
        public static System.Drawing.Point lblSession_Location {
            get {
                object obj = ResourceManager.GetObject("lblSession.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Size semblable à {Width=96, Height=13}.
        /// </summary>
        public static System.Drawing.Size lblSession_Size {
            get {
                object obj = ResourceManager.GetObject("lblSession.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 2.
        /// </summary>
        public static int lblSession_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblSession.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de la session:.
        /// </summary>
        public static string lblSession_Text {
            get {
                return ResourceManager.GetString("lblSession.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=272,Y=16}.
        /// </summary>
        public static System.Drawing.Point lsvSession_Location {
            get {
                object obj = ResourceManager.GetObject("lsvSession.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Size semblable à {Width=267, Height=211}.
        /// </summary>
        public static System.Drawing.Size lsvSession_Size {
            get {
                object obj = ResourceManager.GetObject("lsvSession.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 14.
        /// </summary>
        public static int lsvSession_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lsvSession.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=227,Y=163}.
        /// </summary>
        public static System.Drawing.Point txtCount_Location {
            get {
                object obj = ResourceManager.GetObject("txtCount.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Size semblable à {Width=37, Height=20}.
        /// </summary>
        public static System.Drawing.Size txtCount_Size {
            get {
                object obj = ResourceManager.GetObject("txtCount.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 15.
        /// </summary>
        public static int txtCount_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtCount.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=6,Y=65}.
        /// </summary>
        public static System.Drawing.Point txtNomCours_Location {
            get {
                object obj = ResourceManager.GetObject("txtNomCours.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Size semblable à {Width=168, Height=20}.
        /// </summary>
        public static System.Drawing.Size txtNomCours_Size {
            get {
                object obj = ResourceManager.GetObject("txtNomCours.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 10.
        /// </summary>
        public static int txtNomCours_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtNomCours.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=114,Y=9}.
        /// </summary>
        public static System.Drawing.Point txtSession_Location {
            get {
                object obj = ResourceManager.GetObject("txtSession.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Size semblable à {Width=443, Height=20}.
        /// </summary>
        public static System.Drawing.Size txtSession_Size {
            get {
                object obj = ResourceManager.GetObject("txtSession.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Int32 semblable à 1.
        /// </summary>
        public static int txtSession_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtSession.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
